project:
  type: website
  output-dir: docs

website:
  title: "Vinicius Lima"
  navbar: 
    background: "#f5f5f5"
    foreground: dark
    linkcolor: black
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd        
      - text: "About me"
        file: about.qmd
    right:
      - icon: envelope
        href: mailto:vinicius.lima@mackenzie.br
  
  page-footer: 
    background: "#E1001E"
    right: >-
      vinicius.lima at mackenzie.br  
    left: >-
      &#169; 2025 Vinicius Lima  

  
format:
  html:
    theme: [lumen, custom.scss]
    css: styles.css
    toc: false
    linkcolor: "#2E2E2E"
    fontsize: 12pt
    mainfont: system-ui
    callout-icon: false
    callout-appearance: minimal
    grid:
      body-width: 900px
    
    
  


