project:
  type: website
  output-dir: docs

website:
  title: "Vinicius Lima"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      
format:
  html:
    theme: flatly
    css: styles.css
    fontsize: 1em

editor: visual

