project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd  
      
format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    fontsize: 0.9em

editor: visual

