project:
  type: website
  output-dir: docs

website:
  title: ""
      
format:
  html:
    theme: simplex
    css: styles.css
    toc: false
    fontsize: 14pt
    mainfont: Sans Serif
    

editor: visual

