---
title: "Research"
---

```{=html}
<style>
  details{
    padding: 7pt;
  }
details[open]{
    background: #eeeeee;
}
</style>
```
## Working Papers

**Group size, member selection, and performance: Evidence from legislative elections in Brazil**

(*Submitted*)

<details>

<summary style="font-size:12pt">

Abstract [\[Manuscript\]](#)

</summary>

<p style="font-size:10pt" align="justify">

This paper provides empirical evidence on the causal effects of group size on member selection and performance. Using data from local legislative elections in Brazil in a difference-in-differences framework, I explore an electoral reform that reduced the maximum number of candidates allowed in coalitions disputing legislative seats. The reform did not change the number of candidates and parties in the election, which was possible because in municipalities affected by the new cap parties reorganized into 21% more coalitions than would be expected without the reform. I discuss how the heterogeneity of the candidates combined with the characteristics of the coalitions' production functions led to the recruitment of candidates who were 13% wealthier and the election of city councilors who were 17% wealthier, on average. The reform achieved the goal of reducing campaign costs, which fell by 9%. However, the election of wealthier politicians is an unintended consequence that is in the opposite direction of reducing the power of money in politics.

</p>

</details>

**Peer Effects in Active Learning** (*with [Vladimir Ponczek](https://sites.google.com/site/vponczek/) and [Priscilla Tavares](https://eesp.fgv.br/integrante/priscilla-albuquerque-tavares)*)

(*Submitted*)

<details>

<summary style="font-size:12pt">

Abstract [\[Manuscript\]](files/lima_ponczek_tavares_2024.pdf)

</summary>

<p align="justify">

This paper studies peer effects in an active learning environment, where peer interaction is a meaningful learning mechanism. Identification of peer effects relies on the random assignment of students to different disciplines in a higher education institution. We leverage random variation in the peers' ability distribution across groups and in the frequency at which peers meet for group work and show that social proximity among peers is increasing in the number of groups the students share and in how close they are in terms of their predetermined ability. Our main results show that replacing a socially distant peer with a closer one increases the average score of low-ability students in written exams by 2.8%. Also, the probability that low-ability students receive an evaluation corresponding to outstanding performance in group work increases by 30%, which demonstrates that social proximity makes them exert more effort. There are no detectable effects on the high-ability students' grades. This highlights the importance of peer interaction in positive peer effects on the academic performance of low-skilled individuals.

</p>

</details>

**Domestic Violence Law Enforcement and Women's Labor Market Participation**

<details>

<summary style="font-size:12pt">

Abstract [\[Manuscript\]](#)

</summary>

<p style="font-size:10pt" align="justify">

This paper uses Brazilian data to investigate the effects of a law aimed at tackling domestic violence on women's labor market participation in a difference-in-differences framework. The law increased the probability of punishment of DV perpetrators, and the paper's main hypothesis is that it improved women's negotiating position within households, leading to a redistribution of bargaining power in favor of them. The identification strategy leverages spatial heterogeneity in the access to police stations, the first step into the justice system. The paper's main finding shows that after the policy, married women living at an average distance of 2.7 km from a police station (the 90th percentile) would have experienced a 2.9% increase in their labor market participation rate had they lived at an average of 1.1 km (the 10th percentile). I show supporting evidence of reduced women's hospitalization due to violence and that reporting of crimes related to domestic violence responded consistently. These findings shed light on the interplay between law enforcement, household dynamics, and labor market outcomes.

</p>

</details>

## Work in Progress

Tit-for-Tat between Legislative and Executive (*with [Eduardo Ferraz](https://sites.google.com/view/eduardoferraz/) and [Lucas Finamor](https://lucasfinamor.github.io/)*)

Corruption Disclosure and the Dynamics of Government Coalitions

The Impact of Alternative Dispute Resolution Mechanisms on Violence Against Women (*with [Giovanna Úbida](https://www.giovannaubida.com/)*)
